global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout:    10s

scrape_configs:
  - job_name: 'orderer'
    scheme: https
    tls_config:
      key_file: /etc/prometheus/orderer-clientKey
      cert_file: /etc/prometheus/orderer-clientCert
      ca_file: /etc/prometheus/orderer-caCert
    static_configs:
      - targets: ['orderer.delphi:8443'] # replace with your config
  - job_name: 'peer'
    scheme: https
    tls_config:
      key_file: /etc/prometheus/peer-clientKey
      cert_file: /etc/prometheus/peer-clientCert
      ca_file: /etc/prometheus/peer-caCert
    static_configs:
      - targets: ['peer0.astri.org:9443'] # replace with your config
